# Generated by Django 4.0.4 on 2022-06-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sireproj', '0002_questn_alter_vesseldisc_vtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questn',
        ),
    ]
