# Generated by Django 4.0.5 on 2022-06-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sireproj', '0004_qtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qtion',
            old_name='FText',
            new_name='Ftext',
        ),
    ]
