# Generated by Django 4.0.5 on 2022-07-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sireproj', '0005_rename_ftext_qtion_ftext'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qtion',
            new_name='Question',
        ),
    ]
